openapi: 3.1.0
info:
  title: mikatan API
  version: "1.0"
  description: みかたんにってぃんぐのAPI仕様書です
  contact:
    name: Daichi Sugiyama
servers:
  - url: https://mikatan_knitting/v1
    description: Production
  - url: http://localhost:8080/v1
    description: Local
paths:
  /items:
    $ref: "./paths/item/items.yaml"
  /items/{item_id}:
    $ref: "./paths/item/items_itemId.yaml"
tags:
  - name: items
    description: 商品に関するAPI群
