openapi: 3.1.0
info:
  title: mikatan API
  version: "1.0"
  description: みかたんにってぃんぐのAPI仕様書です
  contact:
    name: Daichi Sugiyama
paths:
  /v1/items/{id}:
    $ref: "paths/item/items.yaml"
tags:
  - name: items
    description: 商品に関するAPI群
