name: run tests
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    services:
      mysql:
        image: mysql:8.4.5
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Go Setup
        uses: actions/setup-go@v5
        with:
          # TODO: use the version from go.mod
          # https://github.com/actions/setup-go?tab=readme-ov-file#getting-go-version-from-the-gomod-file
          go-version: 1.23.4
          cache: true

      - name: Copy Env File
        shell: bash
        run: |
          cp .env.example .env
          cp .env.example ./backend/.env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" | tee .env ./backend/.env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" | tee .env ./backend/.env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" | tee .env ./backend/.env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" | tee .env ./backend/.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" | tee .env ./backend/.env
          echo "MYSQL_TEST_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" | tee .env ./backend/.env
          echo "MYSQL_TEST_HOST=localhost" | tee .env ./backend/.env
          echo "MYSQL_TEST_PORT=3306" | tee .env ./backend/.env
          echo "MYSQL_TEST_DATABASE=${{ secrets.MYSQL_DATABASE }}" | tee .env ./backend/.env
          echo "DSN=${{ secrets.DSN }}" | tee .env ./backend/.env

      - name: Run Test
        run: |
          # .env
          cat 
          cd backend
          go test ./...
