name: run tests
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

# defaults:
#   run:
#     working-directory: backend

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Go Setup
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
          cache: true

      - name: Copy Env File
        run: |
          cp .env.example .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "DSN=${{ secrets.DSN }}" >> .env

      - name: Run Test
        run: |
          # .env
          cat .env
          cd backend
          go test ./...
